# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks

# Global properties
separator_block_width=15

[spotify]
label=
command=~/.i3/spotify.sh
interval=5

[volume]
label=♪
instance=Master
command=/usr/share/i3blocks/volume
interval=1
signal=10

[wireless]
instance=wlan0
command=/usr/share/i3blocks/network
interval=10

[battery]
label=⚡
command=/usr/share/i3blocks/battery
interval=30

[time]
command=date '+%H:%M %d/%m/%y'
interval=60
